### ISSUE TITLE
Main Weapon

### ISSUE THREAD

**Issue by MarsMoon81** [Gh0st352/DNA-Keycards-eEditor#9]
Hello Ghost,
I was wondering if there an error with weapons? When I created the weapons for red down to yellow, it shows up in the files, but in game it doesnt show up at all. 
{
      "dna_Tier": "Red",
      "dna_WeaponCategory": "main",
      "dna_TheChosenOne": "FOX_AEK971",
      "dna_Magazine": "random",
      "dna_Ammunition": "random",
      "dna_OpticType": "random",
      "dna_Suppressor": "random",
      "dna_UnderBarrel": "random",
      "dna_ButtStock": "random",
      "dna_HandGuard": "random",
      "dna_Wrap": "random"
    },
    I put the file type, in and for ammo as well, but the weapon doesnt spawn in the crate, all other edits I made will spawn, just not main weapon or side weapon. Just hand guns.

**Comment by MarsMoon81** [comment]
Also something in the Paragon gear and armor types crashes the exe.

**Comment by Gh0st352** [comment]
> Also something in the Paragon gear and armor types crashes the exe.



> Hello Ghost, I was wondering if there an error with weapons? When I created the weapons for red down to yellow, it shows up in the files, but in game it doesnt show up at all. { "dna_Tier": "Red", "dna_WeaponCategory": "main", "dna_TheChosenOne": "FOX_AEK971", "dna_Magazine": "random", "dna_Ammunition": "random", "dna_OpticType": "random", "dna_Suppressor": "random", "dna_UnderBarrel": "random", "dna_ButtStock": "random", "dna_HandGuard": "random", "dna_Wrap": "random" }, I put the file type, in and for ammo as well, but the weapon doesnt spawn in the crate, all other edits I made will spawn, just not main weapon or side weapon. Just hand guns.

Are you able to provide the lists you used to populate the program? (and a video of you reproducing the error if possible?)

Also, please test again ensuring there are not any spaces/whitespace in your added typenames, and only 1 typename per line. 

Thanks!

**Comment by MarsMoon81** [comment]
![Capture11](https://github.com/Gh0st352/DNA-Keycards-eEditor/assets/10989086/2b5ffd21-91a6-4bcc-9623-6b075550dd8e)

**Comment by Gh0st352** [comment]
> ![Capture11](https://private-user-images.githubusercontent.com/10989086/294001637-2b5ffd21-91a6-4bcc-9623-6b075550dd8e.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMDc4OTYsIm5iZiI6MTcwNDMwNzU5NiwicGF0aCI6Ii8xMDk4OTA4Ni8yOTQwMDE2MzctMmI1ZmZkMjEtOTFhNi00YmNjLTk2MjMtNmIwNzU1NTBkZDhlLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDE4NDYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNjViYzY1NTdjNTJiYWU1MTU4OTk5ODNmYWFlZGZkMDEzNmMxMjA0NjZmZjZmYTllODNhMzUyZDdhZGU2MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WGlUXX6388gcONb894Gy9O4KREede5vfmCJIPlySvUc)

Can you pastebin and link or attach those XMLs here? I can't test/reproduce the error without them (the error might originate from the syntax inside your XMLs)

If you aren't comfortable sharing them publicly you can add me on discord and send them there :)
Discord: gh0st352

Thanks!

**Comment by Gh0st352** [comment]
No response from user, can't repro
